<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>AfterDork</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="SkiaSharp" Version="$(SkiaVersion)" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="..\..\..\CastawayChemist\Resources\pauling.png" LogicalName="pauling.png" />
  </ItemGroup>
</Project>
